[package]
name = "segment_tree_allocator_test"
version = "0.1.0"
authors = ["Fay <814750204@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.0"
bitflags = "1.2.1"