[package]
name = "buddy_system_test"
version = "0.1.0"
authors = ["Fay <814750204@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#buddy_system_allocator = "0.3.9"